config/routes.rb
Rails.application.routes.draw do
   devise_for :customers
  devise_for :admins

  namespace :public do
    resources :items,only:[:index,:show,:create]
    resources :homes,only:[:index]
    resources :addresses,only:[:index,:create,:update,:edit,:destroy]
    resources :cart_items,only:[:show,:create,:update,:index,:destroy]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as:'cart_items_destroy_all'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/conprate' => 'orders#conprate'
    resources :orders
     patch '/customers/unsubscribe' => 'customers#unsubscribe',as:'customers_unsubscribe'
     delete '/customers/withdraw' => 'customers#destroy'
     get '/customers/mypage' => 'customers#show'
    resources :customers, :except => [:new,:index,:show]
    resources :order_details,only:[:create]
  end
  namespace :admin do
    get  'sign_in' => 'sessions#new'
    resources :items, only: [:create, :index, :show, :edit, :update, :destroy,:new]
    resources :genres, only: [:index, :create,:edit, :update]
    resources :customers, only: [:index,:create,:new, :update,:destroy,:show,:edit]
    resources :orders, only: [:show,:update,:new,:index]
    resources :order_details
  end
  root  'admin/items#top'
  get 'about' =>'admin/items#about'
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer
    def full_name
        self.address + self.name + self.postal_code
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  def name
    self.last_name + self.first_name
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses,dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    belongs_to :genre
    has_many :order_items, dependent: :destroy
    has_many :cart_items, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
   belongs_to :order
   belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def edit
    @customer = current_customer
  end


  def show
    @customer = current_customer
  end

  def update
    @customer = current_customer
   if @customer.update(customer_params)
    redirect_to admin_customers_path
    else
    render :edit
  end
  end

  private
    def customer_params
      params.require(:customer).permit(:name,:email,:first_name,:last_name_kana,:last_name,:first_name_kana,:address,:postal_code,:telephone_number,:is_active)
    end
end

app/controllers/admin/homes_controller.rb
def about
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

   def top
    @items = Item.order(created_at: :desc).limit(4)
    @item = Item.new
    @customer = Customer.all
   end


  def new
    @item = Item.new
    @genres = Genre.all
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def create
    @genres = Genre.all
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @genre =Genre.find(@item.genre_id)
  end

  def edit
    @item = Item.find(params[:id])
    @genre =Genre.all
  end

  def update
    @item = Item.find(params[:id])
  if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
  else
    render :update
  end
  end

   private

  def item_params
    params.require(:item).permit(:image,:name, :caption,:genre_id,:price, :is_active,:item_id,:introduction)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected


  def after_sign_out_path_for(resource)
   root_path
  end

  def application
     @customer = current_customer
  end



  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path(resource)
    when Customer
     public_items_path(resource)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:first_name,:last_name_kana,:last_name,:first_name_kana,:address,:postal_code,:email,:telephone_number,:is_deleted])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
   :admin
end

def resource
   @resource ||= Admin.new
end

def devise_mapping
   @devise_mapping ||= Devise.mappings[:admin]
end

end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="edit-title">
        <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
      </div>
      <%= form_for (@customer),url:  admin_customer_path do |f| %>
         <div class="customer-list d-flex">
            <div class="customer-left">
              <div class="customer-item">
                <p class="m-4">会員ID</p>
                <p class="m-4">名前</p>
                <p class="m-4">フリガナ</p>
                <p class="m-4">郵便便番号(ハイフンなし)</p>
                <p class="m-4">住所</p>
                <p class="m-4">電話番号(ハイフンなし)</p>
                <p class="m-4">メールアドレス</p>
                <p class="m-4">会員ステータス</p>
              </div>
            </div>
              <div class="customer-right">
                  <p class="customer-id mt-4"><%= @customer.id %></p>
                <div class="customer-name d-flex">
                  <p>(姓)　<%= f.text_field :last_name %></p>
                  <p>(名)　<%= f.text_field :first_name %></p>
                </div>
                  <div class="customer-name2 d-flex">
                    <p>(セイ) <%= f.text_field :last_name_kana %></p>
                    <p>(メイ) <%= f.text_field :first_name_kana %></p>
                  </div>
                  <div class="customer-postal_code ml-4 mt-2 mb-3">
                    <%= f.text_field :postal_code %>
                  </div>
                    <div class="customer-street-address ml-4 mt-3 mb-3">
                      <%= f.text_field :address %>
                    </div>
                      <div class="customer-phone mt-4 mb-3 ml-4">
                        <%= f.telephone_field :telephone_number %>
                      </div>
                        <div class="customer-email ml-4 mt-3 mb-3">
                          <%= f.text_field :email %>
                        </div>
                          <div class="customer-delete d-flex ml-4">
                            <div class="customer-ture f-flex m-2">
                              <%= f.radio_button :is_active, :true %>
                              <%= f.label :is_active, "有効"  %>
                            </div>
                            <div class="customer-false f-flex m-2">
                              <%= f.radio_button :is_active, :false %>
                              <%= f.label :is_active, "退会" %>
                            </div>
                          </div>
                </div>
            </div>
            <div class="customer-submit">
              <%= f.submit '変更を保存' ,:class=>"bg-success text-white border border-light",:style=>"padding:5px 5px" %>
            </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="customer-index text-center" style="width:15%; margin-left:10%; margin-bottom:3%;">
        <h4 class="bg-light">会員一覧</h4>
      </div>
          <table class="table mx-auto" style="width:80%;">
            <thead class="bg-light">
              <tr>
                <th>会員ID</th>
                <th>氏名</th>
                <th>メールアドレス</th>
                <th>ステータス</th>
              </tr>
            </thead>
            <% @customers.each do |customer| %>
              <tbody>
                <tr>
                  <td><%= customer.id %></td>
                  <td><%= link_to  customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
                  <td><%= customer.email %></td>
                  <% if customer.is_active == true %>
                 <td class="text-success">有効</td>
                  <% else %>
                  <td class="text-success">退会</td>
                  <% end %>
                </tr>
              </tbody>
            <% end %>
          </table>
          <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
 <div class="container">
   <div class="row">
     <div class="row">
      <div class="edit-title">
        <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
      </div>
         <div class="customer-list d-flex">
            <div class="customer-left">
              <div class="customer-item">
                <p class="m-4">名前</p>
                <p class="m-4">フリガナ</p>
                <p class="m-4">メールアドレス</p>
                <p class="m-4">郵便便番号(ハイフンなし)</p>
                <p class="m-4">住所</p>
                <p class="m-4">電話番号(ハイフンなし)</p>
                <p class="m-4">メールアドレス</p>
                <p class="m-4">会員ステータス</p>
              </div>
            </div>
              <div class="customer-right">
                <div class="customer-name  m-4">
                  <%= @customer.last_name + @customer.first_name %>
                </div>
                  <div class="customer-name2  m-4">
                    <%= @customer.last_name_kana + @customer.first_name_kana %>
                  </div>
                <div class="customer-email m-4">
                  <%= @customer.email %>
                </div>
                  <div class="customer-postal_code m-4">
                    <%= @customer.postal_code %>
                  </div>
                    <div class="customer-street-address m-4">
                      <%= @customer.address %>
                    </div>
                      <div class="customer-phone m-4">
                        <%= @customer.telephone_number %>
                      </div>
                        <div class="customer-email m-4">
                          <%= @customer.email %>
                        </div>
                          <div class="customer-delete  m-4">
                            <% if @customer.is_active == true %>
                           <td class="text-success">有効</td>
                            <% else %>
                            <td class="text-success">退会</td>
                            <% end %>
                          </div>
                </div>
            </div>
            <div class="customer-submit d-flex">
              <div class="customer-edit"><%= link_to '編集する',edit_admin_customer_path(@customer) %></div>

<%= link_to "button1",admin_order_path(button: "1") %>
<%= link_to "button2",admin_order_path(button: "2") %>
            </div>
     </div>
   </div>
 </div>