config/routes.rb
Rails.application.routes.draw do
   devise_for :customers
  devise_for :admins

  namespace :public do
    resources :items,only:[:index,:show,:create]
    resources :homes,only:[:index]
    resources :addresses,only:[:index,:create,:update,:edit,:destroy]
    resources :cart_items,only:[:show,:create,:update,:index,:destroy]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as:'cart_items_destroy_all'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/conprate' => 'orders#conprate'
    resources :orders
     patch '/customers/unsubscribe' => 'customers#unsubscribe',as:'customers_unsubscribe'
     delete '/customers/withdraw' => 'customers#destroy'
     get '/customers/mypage' => 'customers#show'
    resources :customers, :except => [:new,:index,:show]
    resources :order_details,only:[:create]
  end
  namespace :admin do
    get  'sign_in' => 'sessions#new'
    resources :items, only: [:create, :index, :show, :edit, :update, :destroy,:new]
    resources :genres, only: [:index, :create,:edit, :update]
    resources :customers, only: [:index,:create,:new, :update,:destroy,:show,:edit]
    resources :orders, only: [:show,:update,:new,:index]
    resources :order_details
  end
  root  'admin/items#top'
  get 'about' =>'admin/items#about'
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer
    def full_name
        self.address + self.name + self.postal_code
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  def name
    self.last_name + self.first_name
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses,dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    belongs_to :genre
    has_many :order_items, dependent: :destroy
    has_many :cart_items, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
   belongs_to :order
   belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
     @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :new
    end
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

   private

  def genre_params
    params.require(:genre).permit(:name,:genre_id )
  end
end

app/controllers/admin/homes_controller.rb
def about
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

   def top
    @items = Item.order(created_at: :desc).limit(4)
    @item = Item.new
    @customer = Customer.all
   end


  def new
    @item = Item.new
    @genres = Genre.all
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def create
    @genres = Genre.all
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @genre =Genre.find(@item.genre_id)
  end

  def edit
    @item = Item.find(params[:id])
    @genre =Genre.all
  end

  def update
    @item = Item.find(params[:id])
  if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
  else
    render :update
  end
  end

   private

  def item_params
    params.require(:item).permit(:image,:name, :caption,:genre_id,:price, :is_active,:item_id,:introduction)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected


  def after_sign_out_path_for(resource)
   root_path
  end

  def application
     @customer = current_customer
  end



  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path(resource)
    when Customer
     public_items_path(resource)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:first_name,:last_name_kana,:last_name,:first_name_kana,:address,:postal_code,:email,:telephone_number,:is_deleted])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
   :admin
end

def resource
   @resource ||= Admin.new
end

def devise_mapping
   @devise_mapping ||= Devise.mappings[:admin]
end

end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= form_with model: @genre, url: admin_genre_path(@genre) do |f| %>
        <div class="genre-edit-title p-4 mx-4">
          <h4 class="text-center  bg-light" style="width:20%;">ジャンル編集</h4>
        </div>
          <div class="genre-edit-list d-inline-flex">
            <div class="genre-edit-ganre p-4">ジャンル名</div>
            <div class="genre-edit-name p-4"><%= f.text_field :name %></div>
            <div class="genre-edit-submit p-4"><%= f.submit '変更を保存' %></div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="genre">
        <div class="genre-title p-4">
          <h4 class="bg-light w-25 text-center">ジャンル一覧・追加</h4>
        </div>
        <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <div class="genre-other d-flex m-4">
          <div class="genre-item pr-4">
            ジャンル名
          </div>
            <div class="genre-text pr-4">
              <%= f.text_field :name,:placeholder=>"ジャンル名" %>
            </div>
              <div class="genre-submit">
                <%= f.submit '新規登録',class:"bg-success rounded text-light" %>
              </div>
        </div>
        <% end %>
      </div>
      <div class="genre-table pt-4">
          <table class="table w-50">
            <thead class="bg-light">
              <tr>
                <th>ジャンル</th>
                <th></th>
              </tr>
            </thead>
             <% @genres.each do |genre| %>
              <tbody>
                <tr>
                  <td><%= genre.name %></td>
                  <td><%= link_to '編集する',edit_admin_genre_path(genre),class: "p-2 rounded bg-success text-light"%></td>
                </tr>
              </tbody>
              <% end %>
          </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/about.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <h1 class="m-3">About</h1>
        <p class="m-3">ながのCAKEは全国発送可能なケーキ屋さんです。<br/>
        お子様からお年寄りの方までお召し上がりいただけるよう、<br/>
        様々なバリエーションをご用意しております<br/>
        また、全国へ発注可能ですので「いつ」でも「どこでも」ご注文いただけます。<br/>
        ぜひご注文ください</p>
           <div class="about-img m-3"><%= image_tag 'ケーキ.jpeg',style:"width:600px; height:200px;" %></div>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
 <div class="container">
   <div class="row">
     <div class="col">
      <div class="new-product">
        <div class="new-product-title m-4 bg-light text-center" style="width:20%;">
          <h4>商品新規登録</h4>
        </div>
          <%= form_for (@item),url: admin_item_path(@item.id) do |f| %>
            <div class="new-product-all text-center w-50 mx-auto m-4">
              <div class="new-product-img d-flex w-80">
                <p class="pr-5 pt-2">商品画像</p>
                <div class="product-img pl-5 pt-2"><%= f.attachment_field :image %></div>
              </div>
                <div class="new-product-name d-flex text-center">
                  <p class="pr-5 text-center">商品名　</p>
                  <div class="product-name pl-5"><%= f.text_field :name,:placeholder=>"商品名" %></div>
                </div>
                  <div class="new-product-introduction d-flex">
                    <p class="pr-5">商品説明</p>
                    <div class="product-introduction pl-5"><%= f.text_area :introduction,:placeholder=>"ここに説明文を記述します。",:class=>"introduction-img" %></div>
                  </div>
                    <div class="new-product-price d-flex pr-5">
                      <p class="pr-5">税抜価格</p>
                      <div class="product-price pl-5"><%= f.text_field :price,:placeholder=>"1000" %>円</div>
                    </div>
                      <div class="new-product-genre d-flex">
                        <p class="pr-5">ジャンル</p>
                        <div class="pl-5 product-genre"><%= f.collection_select(:genre_id, @genre, :id, :name) %></div>
                      </div>
                         <div class="field d-flex">
                            <p class="pr-5">販売ステータス</p>
                              <div class="field-title">
                                <%= f.radio_button :is_active,:true %>
                                <%= f.label :is_active, "販売中", {style: "display: inline-block;"} %>
                                <%= f.radio_button :is_active,:false %>
                                <%= f.label :is_active, "販売停止中", {style: "display: inline-block;"} %>
                              </div>
                          </div>
                           <div class="new-product-submit m-3"><%= f.submit '編集を保存',:class=>"text-white bg-success border border-white rounded px-4 py-2" %></div>
                </div>
              <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="item-title m-4 text-center" style="width:15%;">
        <h4 class="bg-light">商品一覧</h4>
      </div>
        <table class="table">
          <div class="table-header">
            <thead>
              <tr>
                <th>商品ID</th>
                <th>商品名</th>
                <th>税抜価格</th>
                <th>ジャンル名</th>
                <th>ステータス</th>
              </tr>
            </thead>
          </div>
          <div class="table-list">
            <tbody>
            <% @items.each do |item| %>
              <tr>
                <td><%= item.id %></td>
                <td><%= item.name %></td>
                <td><%= item.price %></td>
                <td><%= item.genre.name %></td>
                   <% if item.is_active == true %>
                      <td class="pt-4 pl-2 text-success">販売中</td>
                    <% else %>
                      <td class="pt-4 pl-2 text-success">販売停止中</td>
                    <% end %>
              </tr>
                </tbody>
            <% end %>
            </div>
        </table>
          <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
 <div class="container">
   <div class="row">
     <div class="col">
      <div class="new-product">
        <div class="new-product-title m-4 bg-light text-center" style="width:20%;">
          <h4>商品新規登録</h4>
        </div>
          <%= form_for (@item),url: admin_items_path do |f| %>
            <div class="new-product-all text-center w-50 mx-auto m-4">
              <div class="new-product-img d-flex w-80">
                <p class="pr-5 pt-2">商品画像</p>
                <div class="product-img pl-5 pt-2"><%= f.attachment_field :image %></div>
              </div>
                <div class="new-product-name d-flex text-center">
                  <p class="pr-5 text-center">商品名　</p>
                  <div class="product-name pl-5"><%= f.text_field :name,:placeholder=>"商品名" %></div>
                </div>
                  <div class="new-product-introduction d-flex">
                    <p class="pr-5">商品説明</p>
                    <div class="product-introduction pl-5"><%= f.text_area :introduction,:placeholder=>"ここに説明文を記述します。",:class=>"introduction-img" %></div>
                  </div>
                    <div class="new-product-price d-flex pr-5">
                      <p class="pr-5">税抜価格</p>
                      <div class="product-price pl-5"><%= f.text_field :price,:placeholder=>"1000" %>円</div>
                    </div>
                      <div class="new-product-genre d-flex">
                        <p class="pr-5">ジャンル</p>
                        <div class="pl-5 product-genre"><%= f.collection_select(:genre_id, @genres, :id, :name) %></div>
                      </div>
                         <div class="field d-flex">
                            <p class="pr-5">販売ステータス</p>
                              <div class="field-title">
                                <%= f.radio_button :is_active,:true %>
                                <%= f.label :is_active, "販売中", {style: "display: inline-block;"} %>
                                <%= f.radio_button :is_active,:false %>
                                <%= f.label :is_active, "販売停止中", {style: "display: inline-block;"} %>
                              </div>
                          </div>
                           <div class="new-product-submit m-3"><%= f.submit '新規登録',:class=>"text-white bg-success border border-white rounded px-4 py-2" %></div>
                </div>
              <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/items/show.html.erb
<div class="container">
  <h4 class="text-center bg-light m-4" style="width:15%;">商品詳細</h4>
    <div class="row pt-4" style="display:block;">
        <div class="new-product-show d-flex">
            <div class="product-show-item p-4">
              <%= attachment_image_tag @item,:image, fallback: "no_image.jpg", size:'200x200' %>
            </div>
                <div class="product-show-name p-4">
                  <p class="p-2">商品名</p>
                  <p class="p-2">商品説明</p>
                  <p class="p-2">ジャンル</p>
                  <p class="p-2",style="font-size:10px;">税込価格<br/>(税抜価格)</p>
                  <p>販売ステータス</p>
                </div>
                  <div class="product-show-introduction p-4"> 
                    <div><p class="p-2"><%= @item.name %></p></div>
                    <div><p class="p-2"><%= @item.introduction %></p></div>
                    <div><p class="p-2"><%= @item.genre.name %></p></div>
                    <div><p class="p-2"><%= @item.price %></p></div>
                    <div>
                      <% if @item.is_active == true %>
                        <p class="pt-4 pl-2 text-success">販売中</p>
                      <% else %>
                        <p class="pt-4 pl-2 text-success">販売停止中</p>
                      <% end %>
                    </div>
                  </div>
        </div>
          <div class="product-show-edit w-50" style="margin-left:33%; margin-top:20px;">
            <%= link_to "編集",edit_admin_item_path,class:"text-center bg-success text-light px-4 py-2 rounded-lg" %>
          </div>
    </div>
</div>

app/views/admin/items/top.html.erb
<div class="container">
  <div class="row p-2">
    <div class="col m-4">
      <div class="top-title">
        <div class="top-img position-relative text-center">
          <%= image_tag 'img2.jpeg',style:"width:600px; height:200px;" %>
          <div class="top-list bg-white position-absolute text-left" style=" top: 50%; left: 50%; transform: translate(-50%, -50%); -webkit-transform: translate(-50%, -50%); -ms-transform: translate(-50%, -50%);">
            <p>ようこそ、長野CAKEへ<br/>
            このサイトは、ケーキ販売のECサイトになります。<br/>
            会員でない方も観覧できますが、<br/>
            購入には会員登録が必要になります。</p>
          </div>
        </div>
      </div>
        <div class="top-logo">
          <h4 class="my-3 font-weight-bold">新着商品</h4>
        </div>
          <div class="top-all d-flex">
            <% @items.each do |item| %>
              <div class="top-other d-block m-4 text-center">
                <div class="top-item"><%= attachment_image_tag item,:image, fallback: "no_image.jpg", size:'200x200' %></div>
                <p><%= item.name %></p>
                <p>¥<%= item.price %></p>
              </div>
            <% end %>
          </div>
         <% if customer_signed_in? %>
            <div class="top-link text-right">
              <%= link_to '全ての商品をみる',  public_items_path %>
            </div>
              <% else %>
               <%= link_to '全ての商品をみる',  new_customer_registration_path %>
          <% end %>
    </div>
  </div>
</div>