config/routes.rb
Rails.application.routes.draw do
   devise_for :customers
  devise_for :admins

  namespace :public do
    resources :items,only:[:index,:show,:create]
    resources :homes,only:[:index]
    resources :addresses,only:[:index,:create,:update,:edit,:destroy]
    resources :cart_items,only:[:show,:create,:update,:index,:destroy]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as:'cart_items_destroy_all'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/conprate' => 'orders#conprate'
    resources :orders
     patch '/customers/unsubscribe' => 'customers#unsubscribe',as:'customers_unsubscribe'
     delete '/customers/withdraw' => 'customers#destroy'
     get '/customers/mypage' => 'customers#show'
    resources :customers, :except => [:new,:index,:show]
    resources :order_details,only:[:create]
  end
  namespace :admin do
    get  'sign_in' => 'sessions#new'
    resources :items, only: [:create, :index, :show, :edit, :update, :destroy,:new]
    resources :genres, only: [:index, :create,:edit, :update]
    resources :customers, only: [:index,:create,:new, :update,:destroy,:show,:edit]
    resources :orders, only: [:show,:update,:new,:index]
    resources :order_details
  end
  root  'admin/items#top'
  get 'about' =>'admin/items#about'
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer
    def full_name
        self.address + self.name + self.postal_code
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  def name
    self.last_name + self.first_name
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses,dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    belongs_to :genre
    has_many :order_items, dependent: :destroy
    has_many :cart_items, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
   belongs_to :order
   belongs_to :item
end

app/controllers/admin/homes_controller.rb
def about
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected


  def after_sign_out_path_for(resource)
   root_path
  end

  def application
     @customer = current_customer
  end



  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path(resource)
    when Customer
     public_items_path(resource)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:first_name,:last_name_kana,:last_name,:first_name_kana,:address,:postal_code,:email,:telephone_number,:is_deleted])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
   :admin
end

def resource
   @resource ||= Admin.new
end

def devise_mapping
   @devise_mapping ||= Devise.mappings[:admin]
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="d-flex justify-content-between">
      <div class="header-logo">
        <h2 class="px-4 py-2 m-4  border border-dark">LOGO</h2>
      </div>
      <div class="header-item d-flex mt-2">
      <% if customer_signed_in? %>
      <p class="m-4">ようこそ<%= current_customer.name %>さん</p>
        <li class="m-4" style="list-style:none;"><%= link_to 'マイページ' ,  public_customers_mypage_path, :class=>"text-dark" %></li>
        <li class="m-4" style="list-style:none;"><%= link_to '商品一覧', public_items_path,:class=>"text-dark" %></li>
        <li class="m-4" style="list-style:none;"><%= link_to 'カート',  public_cart_items_path,:class=>"text-dark" %></li>
        <li class="m-4" style="list-style:none;"><%= link_to 'LOGOUT', destroy_admin_session_path, method: :delete, :class=>"text-dark" %></li>
        <% else %>
        <div class-"customer-sigin-in d-flex mt-2">
          <li class="m-4" style="list-style:none;"><%= link_to "about", about_path %></li>
          <li class="m-4" style="list-style:none;"><%= link_to "商品一覧", public_items_path %></li>
          <li class="m-4" style="list-style:none;"><%= link_to "新規登録",  new_customer_session_path %></li>
          <li class="m-4" style="list-style:none;"><%= link_to "ログイン",  new_customer_registration_path %></li>
        </div>
      <% end %>
      </div>
    </header>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>